# Generated by Django 4.0 on 2022-01-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeles', models.CharField(max_length=125, verbose_name='Modèles')),
                ('marque', models.CharField(max_length=125, verbose_name='Marque')),
                ('refregiration', models.CharField(max_length=125, verbose_name='Réfrigiration')),
                ('puissance_nominale', models.CharField(max_length=125, verbose_name='Puissance nominale')),
                ('volume_balaye', models.CharField(max_length=125, verbose_name='Volume Balayé')),
                ('diametre_aspiration', models.CharField(max_length=125, verbose_name="Diamétre d'aspiration")),
                ('diametre_refoulement', models.CharField(max_length=125, verbose_name='Diamétre de refoulement')),
                ('tupe_huile', models.CharField(max_length=125, verbose_name="Tupe d'huile")),
                ('quantite_huile', models.CharField(max_length=125, verbose_name="Quantité d'huile")),
                ('longeur', models.CharField(max_length=125, verbose_name='Longeur')),
                ('largeur', models.CharField(max_length=125, verbose_name='Largeur')),
                ('hauteur', models.CharField(max_length=125, verbose_name='Hauteur')),
                ('poids', models.CharField(max_length=125, verbose_name='Poids')),
                ('technologie_compresseur', models.CharField(max_length=125, verbose_name='Technologie du compresseur')),
                ('application', models.CharField(max_length=125, verbose_name='Application')),
                ('voltage', models.CharField(max_length=125, verbose_name='Voltage')),
                ('protecteur', models.CharField(max_length=125, verbose_name='Protecteur')),
                ('code_moteur', models.CharField(max_length=125, verbose_name='Code du moteur')),
                ('intensite_max', models.CharField(max_length=125, verbose_name='Intensité max de fonctionnement')),
                ('intensite_rotor', models.CharField(max_length=125, verbose_name='Intensité rotor bloqué')),
                ('frequence', models.CharField(max_length=125, verbose_name='Fréquence')),
            ],
        ),
    ]
