# Generated by Django 4.0 on 2022-01-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='code_moteur',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='intensite_max',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='intensite_rotor',
        ),
        migrations.AddField(
            model_name='motor',
            name='code_moteur_1PH',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Code du moteur 1PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='code_moteur_3PH',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Code du moteur 3PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='intensite_max_1PH',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Intensité max pour 1PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='intensite_max_3PH',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Intensité max pour 3PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='intensite_rotor_1PH',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Intensité Rotor Bloqué 1PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='intensite_rotor_3PH',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Intensité Rotor Bloqué 3PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_10',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -10°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_15',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -15°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_20',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -20°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_25',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -25°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_30',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -30°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_35',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -35°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_5',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -5°'),
        ),
    ]
