# Generated by Django 4.0 on 2022-01-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_motor_code_moteur_remove_motor_intensite_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='frequence',
        ),
        migrations.AddField(
            model_name='motor',
            name='frequence_50',
            field=models.CharField(max_length=125, null=True, verbose_name='Fréquence pour 50 Hz'),
        ),
        migrations.AddField(
            model_name='motor',
            name='frequence_60',
            field=models.CharField(max_length=125, null=True, verbose_name='Fréquence pour 60 Hz'),
        ),
    ]
