# Generated by Django 4.0 on 2022-02-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_motor_frequence_motor_frequence_50_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motor',
            old_name='puissance_frigorifique_10',
            new_name='puissance_frigorifique_m10',
        ),
        migrations.RenameField(
            model_name='motor',
            old_name='puissance_frigorifique_15',
            new_name='puissance_frigorifique_m15',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='frequence_50',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='frequence_60',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='intensite_max_1PH',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='intensite_max_3PH',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='intensite_rotor_1PH',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='intensite_rotor_3PH',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='puissance_frigorifique_20',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='puissance_frigorifique_25',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='puissance_frigorifique_30',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='puissance_frigorifique_35',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='puissance_nominale',
        ),
        migrations.AddField(
            model_name='motor',
            name='intensite_max_1PH_50',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='50 HZ Intensité max pour 1PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='intensite_max_1PH_60',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='60 HZ Intensité max pour 1PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='intensite_max_3PH_50',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='50 HZ Intensité max pour 3PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='intensite_max_3PH_60',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='60 HZ Intensité max pour 3PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='intensite_rotor_1PH_50',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='50 HZ Intensité Rotor Bloqué 1PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='intensite_rotor_1PH_60',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='60 HZ Intensité Rotor Bloqué 1PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='intensite_rotor_3PH_50',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='50 HZ Intensité Rotor Bloqué 3PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='intensite_rotor_3PH_60',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='60 HZ Intensité Rotor Bloqué 3PH'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_cv',
            field=models.CharField(max_length=125, null=True, verbose_name='Puissance cv'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_0',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour 0°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_75',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour 7.5°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_m5',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -5°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='type_demar',
            field=models.CharField(max_length=125, null=True, verbose_name='Type de démarrage'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='puissance_frigorifique_5',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour 5°'),
        ),
    ]
