# Generated by Django 4.0 on 2022-02-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_rename_puissance_frigorifique_10_motor_puissance_frigorifique_m10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='modeles',
            field=models.CharField(max_length=125, null=True, unique=True, verbose_name='Modèles'),
        ),
    ]
