# Generated by Django 4.0 on 2022-02-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_motor_modeles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='modeles',
            field=models.CharField(max_length=125, null=True, unique=True, verbose_name='Modèles'),
        ),
    ]
