# Generated by Django 4.0 on 2022-02-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_motor_modeles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='code_moteur_1PH',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='code_moteur_3PH',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='tupe_huile',
        ),
        migrations.AddField(
            model_name='motor',
            name='cylindre',
            field=models.CharField(max_length=125, null=True, verbose_name='Cylindrée cm3'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_m20',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -20°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_m25',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -25°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_m30',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -30°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_m35',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -35°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_m40',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -40°'),
        ),
        migrations.AddField(
            model_name='motor',
            name='puissance_frigorifique_m45',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Puissance Frigorifique pour -45°'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='diametre_aspiration',
            field=models.CharField(max_length=125, verbose_name="Diamétre d'aspiration en pouce"),
        ),
        migrations.AlterField(
            model_name='motor',
            name='diametre_refoulement',
            field=models.CharField(max_length=125, verbose_name='Diamétre de refoulement en pouce'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='hauteur',
            field=models.CharField(max_length=125, verbose_name='Hauteur cm'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='largeur',
            field=models.CharField(max_length=125, verbose_name='Largeur cm'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='longeur',
            field=models.CharField(max_length=125, verbose_name='Longeur cm'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='poids',
            field=models.CharField(max_length=125, verbose_name='Poids kg'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='quantite_huile',
            field=models.CharField(max_length=125, verbose_name="Quantité d'huile L"),
        ),
        migrations.AlterField(
            model_name='motor',
            name='voltage',
            field=models.CharField(max_length=125, verbose_name='Voltage v'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='volume_balaye',
            field=models.CharField(max_length=125, verbose_name='Volume Balayé m3/h'),
        ),
    ]
