# Generated by Django 4.0 on 2022-08-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_remove_motor_code_moteur_1ph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='cylindre',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='diametre_aspiration',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='diametre_refoulement',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='hauteur',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='intensite_max_1PH_60',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='intensite_max_3PH_60',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='intensite_rotor_1PH_50',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='intensite_rotor_1PH_60',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='intensite_rotor_3PH_50',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='intensite_rotor_3PH_60',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='largeur',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='longeur',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='protecteur',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='quantite_huile',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='refregiration',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='technologie_compresseur',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='type_demar',
        ),
    ]
